name: Bug Report
description: File a bug report
title: "[Bug]: "
assignees:
  - hbagdi
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
      render: markdown
    validations:
      required: false
  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version of hit are you running?
      render: shell
    validations:
      required: true
  - type: textarea
    id: hit-file
    attributes:
      label: Hit file to use for reproducing the bug
      description: Please paste the .hit file to use for reproducing the bug.
      render: shell
