run:
  timeout: 5m
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errname
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - gci
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tenv
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
issues:
  exclude-rules:
    - linters:
        - forbidigo
      path: pkg/cmd/
linters-settings:
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json:     camel
        yaml:     camel

