name: CI Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      - name: Setup golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
        with:
          version: v1.44.0
      - name: test
        run: make test
